apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-deploy
  namespace: default
  labels:
    testconfig: uudwi
    envconfigtest: 22rpm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: busybox
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'echo Container 1 is Running ; sleep 3600']
        envFrom:
        - configMapRef:
            name: envconfigtest-22rpm
        volumeMounts:
        - mountPath: /test
          name: testconfig
      volumes:
      - name: testconfig
        configMap:
          name: testconfig-uudwi
