apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: busybox-sts
  namespace: default
  labels:
    testsecret: m0hy9
    envconfigtest: bdkks
spec:
  serviceName: busybox
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: busybox
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'echo Container 1 is Running ; sleep 3600']
        envFrom:
        - configMapRef:
            name: envconfigtest-bdkks
        volumeMounts:
        - mountPath: /test
          name: testsecret
      volumes:
      - name: testsecret
        secret:
          secretName: testsecret-m0hy9
