apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: customsecrets.linkedconfig.pbuilder.io
spec:
  group: linkedconfig.pbuilder.io
  version: v1alpha1
  names:
    kind: CustomSecret
    plural: customsecrets
    singular: customsecret
    shortNames:
    - ccs
  scope: Namespaced
