kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: Configurator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: configurator
subjects:
- kind: ServiceAccount
  name: linkedconfig-service-account
  namespace: default